{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sodapy import Socrata\n",
    "import collections\n",
    "import re\n",
    "from time import time\n",
    "import math\n",
    "import feather\n",
    "from collections import defaultdict\n",
    "import geopandas\n",
    "from datetime import datetime\n",
    "import os\n",
    "import glob\n",
    "from tqdm import tqdm_notebook as tqdm\n",
    "import optuna\n",
    "import shutil\n",
    "import tempfile\n",
    "import tensorflow as tf\n",
    "\n",
    "#Using keras\n",
    "import keras\n",
    "from keras.models import Sequential  \n",
    "from keras.layers import Dense, LSTM, Dropout, TimeDistributed\n",
    "from keras.callbacks import EarlyStopping\n",
    "\n",
    "# others\n",
    "from tqdm import tqdm\n",
    "\n",
    "#from scripts.utils import load_rnn_data\n",
    "pd.options.display.max_columns = 200\n",
    "from scipy import stats\n",
    "from collections import Counter\n",
    "\n",
    "# validation\n",
    "from sklearn.model_selection import StratifiedKFold, train_test_split\n",
    "from sklearn.metrics import accuracy_score,mean_squared_error, log_loss\n",
    "from sklearn.model_selection import TimeSeriesSplit\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from shapely.geometry import Point\n",
    "\n",
    "from copy import deepcopy\n",
    "# others\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_rnn_data(path, window, predict_ts, geo_col=[\"geoid10_tract\"], y_cols=[\"crime\"]):\n",
    "    \"\"\"\n",
    "    y_cols: [\"crime\"] or [\"incident_type_0\", \"incident_type_1\", \"incident_type_2\"]\n",
    "    geo_col: [\"geoid10_tract\"] or [\"geoid10_block\"]\n",
    "    return y_all and x_all of given path\n",
    "    \"\"\"\n",
    "    # load data\n",
    "    df = feather.read_dataframe(path)\n",
    "    df.sort_values(by=[\"datetime\", \"geoid10_tract\"], inplace=True)\n",
    "    df.set_index(\"datetime\", inplace=True)\n",
    "\n",
    "    # input columns\n",
    "    x_cols = list(df.drop(y_cols + geo_col, axis=1).columns)\n",
    "\n",
    "    # group by geoid\n",
    "    geo_grs = df.groupby(by=geo_col)\n",
    "\n",
    "    # arrayes to store x and y\n",
    "    # (window size, input size, no of tracts, no of timesteps)\n",
    "    n_timesteps = int(len(df) / len(geo_grs)) - window - predict_ts + 1\n",
    "    x_all = np.empty(shape=(window, len(x_cols + y_cols), len(geo_grs), n_timesteps))\n",
    "\n",
    "    # (output size, no of tracts, no of timesteps)\n",
    "    y_all = np.empty(shape=(len(y_cols), len(geo_grs), n_timesteps))\n",
    "\n",
    "    # to store geo_ids and y_all's datetime\n",
    "    geo_ids = []\n",
    "\n",
    "    y_datetime = df.index.unique()[window + predict_ts - 1:]\n",
    "\n",
    "    for i, (geo_id, gr) in enumerate(tqdm(geo_grs)):\n",
    "        geo_ids.append(geo_id)\n",
    "        x_values = gr[y_cols + x_cols].values\n",
    "        y_values = gr[y_cols].values\n",
    "\n",
    "        for j in range(window, len(gr) - predict_ts + 1):\n",
    "            # generate x_all\n",
    "            x_all[:, :, i, j - window] = x_values[j - window:j, :]\n",
    "            y_all[:, i, j - window] = y_values[j + predict_ts - 1, :]\n",
    "\n",
    "    return x_all, y_all, geo_ids, y_datetime"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# set configuration\n",
    "path = \"./features/features_binary_tract_2H.feather\"\n",
    "window = 12\n",
    "predict_ts = 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 195/195 [00:21<00:00,  8.07it/s]\n"
     ]
    }
   ],
   "source": [
    "# load data as x and y of RNN\n",
    "x_all, y_all, geo_ids, y_datetime  = load_rnn_data(path, window, predict_ts)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(12, 8, 195, 18600)\n",
      "(1, 195, 18600)\n",
      "195\n",
      "18600\n"
     ]
    }
   ],
   "source": [
    "print(x_all.shape)\n",
    "print(y_all.shape)\n",
    "print(len(geo_ids))\n",
    "print(len(y_datetime))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def time_series_cv(x_all, y_all, n_splits = 5, model=None, fit_params=None, baseline=False):\n",
    "    \"\"\"\n",
    "    :param baseline: True or False (defualt: False)\n",
    "    :return: train and test scores and prediction of y on test data\n",
    "    \"\"\"\n",
    "\n",
    "    # prepare dictionary to store scores\n",
    "    train_scores = {}\n",
    "    metrics = [\"acc\", \"log_loss\"]\n",
    "    for metric in metrics:\n",
    "        train_scores[metric] = []\n",
    "    test_scores = deepcopy(train_scores)\n",
    "\n",
    "    # prepare dictionary to store predictions\n",
    "    y_test_preds = np.empty_like(y_all)\n",
    "\n",
    "    # time series split\n",
    "    tss = TimeSeriesSplit(n_splits=n_splits)\n",
    "\n",
    "    for split, (train_idx, test_idx) in enumerate(tss.split(x_all, y_all)):\n",
    "\n",
    "        print(\"---------- split {0} ----------\".format(split))\n",
    "        print(\"train_index:{0}~{1} test_index:{2}~{3}\".format(train_idx[0], train_idx[-1], test_idx[0], test_idx[-1]))\n",
    "\n",
    "        # create train and test set\n",
    "        x_train = x_all[:train_idx[-1]]\n",
    "        y_train = y_all[:train_idx[-1]]\n",
    "        x_test = x_all[test_idx[0]:test_idx[-1]]\n",
    "        y_test = y_all[test_idx[0]:test_idx[-1]]\n",
    "\n",
    "        if baseline:\n",
    "            # return 0 for all predicted probabiliby\n",
    "            y_train_prob = np.zeros_like(y_train)\n",
    "            y_test_prob = np.zeros_like(y_test)\n",
    "\n",
    "            # return 0 for all binary predictions\n",
    "            y_train_pred = np.zeros_like(y_train)\n",
    "            y_test_pred = np.zeros_like(y_test)\n",
    "\n",
    "        else:\n",
    "            # train\n",
    "            model.fit(x_train, y_train, **fit_params)\n",
    "\n",
    "            # predict\n",
    "            y_train_prob = model.predict(x_train)\n",
    "            y_test_prob = model.predict(x_test)\n",
    "\n",
    "            # convert form probability to binary\n",
    "            y_train_pred = np.fix(y_train_prob)\n",
    "            y_test_pred = np.fix(y_test_prob)\n",
    "\n",
    "        # store test prediction\n",
    "        y_test_preds[test_idx[0]:test_idx[-1]] = y_test_pred\n",
    "\n",
    "        # calculate metrics\n",
    "        train_log_loss = log_loss(y_train.flatten(), y_train_prob.flatten())\n",
    "        test_log_loss = log_loss(y_test.flatten(), y_test_prob.flatten())\n",
    "        train_acc = accuracy_score(y_train.flatten(), y_train_pred.flatten())\n",
    "        test_acc = accuracy_score(y_test.flatten(), y_test_pred.flatten())\n",
    "\n",
    "        # store scores\n",
    "        train_scores[\"log_loss\"].append(train_log_loss)\n",
    "        test_scores[\"log_loss\"].append(test_log_loss)\n",
    "        train_scores[\"acc\"].append(train_acc)\n",
    "        test_scores[\"acc\"].append(test_acc)\n",
    "\n",
    "        print(\"train_log_loss:{} test_log_loss:{}\".format(train_log_loss, test_log_loss))\n",
    "        print(\"train_acc:{} test_acc:{}\\n\".format(train_acc, test_acc))\n",
    "\n",
    "        # convert to dataframe\n",
    "        train_scores_df = pd.DataFrame(train_scores)\n",
    "        test_scores_df = pd.DataFrame(test_scores)\n",
    "\n",
    "    return train_scores_df, test_scores_df, y_test_preds"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# transpose input shape to apply TimeSeriesSplit in time_series_cv\n",
    "# TODO: fix output shape of load_rnn_data\n",
    "if x_all.shape[0] != y_all.shape[0]:\n",
    "    x_all = x_all.T\n",
    "    y_all = y_all.T"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "x_all_tune = x_all[:500]\n",
    "y_all_tune = y_all[:500]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(500, 195, 8, 12)\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Input 0 is incompatible with layer lstm_32: expected ndim=3, found ndim=4",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-33-05e27aa03157>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     14\u001b[0m model.add(TimeDistributed(Dense(8), \n\u001b[1;32m     15\u001b[0m                       input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3])))\n\u001b[0;32m---> 16\u001b[0;31m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mLSTM\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0munits\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m50\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     17\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mDropout\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdropout_rate\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     18\u001b[0m \u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mDense\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0munits\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m195\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mactivation\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"sigmoid\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m//anaconda/lib/python2.7/site-packages/keras/engine/sequential.pyc\u001b[0m in \u001b[0;36madd\u001b[0;34m(self, layer)\u001b[0m\n\u001b[1;32m    179\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minputs\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnetwork\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_source_inputs\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moutputs\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    180\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moutputs\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 181\u001b[0;31m             \u001b[0moutput_tensor\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlayer\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moutputs\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    182\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moutput_tensor\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlist\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    183\u001b[0m                 raise TypeError('All layers in a Sequential model '\n",
      "\u001b[0;32m//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.pyc\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, inputs, initial_state, constants, **kwargs)\u001b[0m\n\u001b[1;32m    530\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    531\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0minitial_state\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0mNone\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mconstants\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 532\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mRNN\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__call__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minputs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    533\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    534\u001b[0m         \u001b[0;31m# If any of `initial_state` or `constants` are specified and are Keras\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.pyc\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, inputs, **kwargs)\u001b[0m\n\u001b[1;32m    412\u001b[0m                 \u001b[0;31m# Raise exceptions in case the input is not compatible\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    413\u001b[0m                 \u001b[0;31m# with the input_spec specified in the layer constructor.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 414\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0massert_input_compatibility\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minputs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    415\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    416\u001b[0m                 \u001b[0;31m# Collect input shapes to build layer.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.pyc\u001b[0m in \u001b[0;36massert_input_compatibility\u001b[0;34m(self, inputs)\u001b[0m\n\u001b[1;32m    309\u001b[0m                                      \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mname\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m': expected ndim='\u001b[0m \u001b[0;34m+\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    310\u001b[0m                                      \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mspec\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mndim\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m', found ndim='\u001b[0m \u001b[0;34m+\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 311\u001b[0;31m                                      str(K.ndim(x)))\n\u001b[0m\u001b[1;32m    312\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mspec\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmax_ndim\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    313\u001b[0m                 \u001b[0mndim\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mK\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mndim\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: Input 0 is incompatible with layer lstm_32: expected ndim=3, found ndim=4"
     ]
    }
   ],
   "source": [
    "# Model\n",
    "# Param\n",
    "dropout_rate = 0.2\n",
    "optimizers = ['softmax', 'adam']\n",
    "hidden_neurons = 50\n",
    "epoch_param = 200\n",
    "validation_split_param = 0.2\n",
    "batch_size_param = 128    \n",
    "\n",
    "print(x_all_tune.shape)\n",
    "\n",
    "\n",
    "model = Sequential()\n",
    "model.add(TimeDistributed(Dense(8), \n",
    "                          input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]))\n",
    "model.add(LSTM(units=hidden_neurons,\n",
    "               input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]),\n",
    "               return_sequences=True))\n",
    "model.add(Dropout(dropout_rate))\n",
    "model.add(Dense(units=195, activation=\"sigmoid\"))\n",
    "model.compile(loss=\"binary_crossentropy\", optimizer=optimizers, metrics=[\"acc\"])\n",
    "\n",
    "early_stop = EarlyStopping(monitor='loss',patience=10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From //anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Colocations handled automatically by placer.\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "time_distributed_1 (TimeDist (None, 195, 8, 8)         104       \n",
      "=================================================================\n",
      "Total params: 104\n",
      "Trainable params: 104\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "model = Sequential()\n",
    "model.add(TimeDistributed(Dense(8), \n",
    "                          input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3])))\n",
    "          \n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "## Set Up Optuna\n",
    "\n",
    "def objective(trial):\n",
    "    \n",
    "    # Param\n",
    "    dropout_rate = 0.2\n",
    "    optimizers = ['softmax', 'adam']\n",
    "    hidden_neurons = 50\n",
    "    epoch_param = 200\n",
    "    validation_split_param = 0.2\n",
    "    batch_size_param = 128\n",
    "    \n",
    "    # Model\n",
    "    model = Sequential()\n",
    "    model.add(TimeDistributed(Dense(8), \n",
    "                          input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3])))\n",
    "    model.add(LSTM(units=hidden_neurons))\n",
    "    model.add(Dropout(dropout_rate))\n",
    "    model.add(Dense(units=195, activation=\"sigmoid\"))\n",
    "    model.compile(loss=\"binary_crossentropy\", optimizer=optimizers, metrics=[\"acc\"])\n",
    "    \n",
    "    early_stop = EarlyStopping(monitor='loss',patience=10)\n",
    "    \n",
    "    fit_params_def = {'batch_size': batch_size_param,\n",
    "                     'epochs': epoch_param,\n",
    "                      'verbose':1, \n",
    "                      'callbacks': [early_stop], \n",
    "                      'validation_split': validation_split_param}\n",
    "    \n",
    "    \n",
    "    # Data\n",
    "    # evaluate log loss and accuracy based on time series cross validation\n",
    "    train_scores_df, test_scores_df, y_test_preds = time_series_cv(x_all_tune,\n",
    "                                                               y_all_tune,\n",
    "                                                               n_splits=5,\n",
    "                                                               model=model,\n",
    "                                                               fit_params=fit_params_def,\n",
    "                                                               baseline=False)\n",
    "    train_score_mean = train_scores_df.mean()['acc']\n",
    "    test_scores_mean = test_scores_df.mean()['acc']\n",
    "\n",
    "    return 1.0 - test_scores_mean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[W 2019-05-02 15:01:13,535] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,551] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_2: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_2: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,561] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_3: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_3: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,571] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_4: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_4: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,582] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_5: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_5: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,600] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_6: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_6: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,613] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_7: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_7: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,624] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_8: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ValueError: Input 0 is incompatible with layer lstm_8: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,636] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_9: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_9: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,647] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_10: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_10: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,657] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_11: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_11: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,669] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_12: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_12: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,681] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_13: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_13: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,692] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_14: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_14: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,703] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_15: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_15: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,716] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_16: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ValueError: Input 0 is incompatible with layer lstm_16: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,728] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_17: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_17: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,738] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_18: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_18: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,749] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_19: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_19: expected ndim=3, found ndim=4\n",
      "[W 2019-05-02 15:01:13,764] Setting trial status as TrialState.FAIL because of the following error: ValueError('Input 0 is incompatible with layer lstm_20: expected ndim=3, found ndim=4',)\n",
      "Traceback (most recent call last):\n",
      "  File \"//anaconda/lib/python2.7/site-packages/optuna/study.py\", line 407, in _run_trial\n",
      "    result = func(trial)\n",
      "  File \"<ipython-input-11-b6bb4a3a8560>\", line 16, in objective\n",
      "    input_shape=(x_all_tune.shape[1], x_all_tune.shape[2], x_all_tune.shape[3]), ))\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/sequential.py\", line 165, in add\n",
      "    layer(x)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/layers/recurrent.py\", line 532, in __call__\n",
      "    return super(RNN, self).__call__(inputs, **kwargs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 414, in __call__\n",
      "    self.assert_input_compatibility(inputs)\n",
      "  File \"//anaconda/lib/python2.7/site-packages/keras/engine/base_layer.py\", line 311, in assert_input_compatibility\n",
      "    str(K.ndim(x)))\n",
      "ValueError: Input 0 is incompatible with layer lstm_20: expected ndim=3, found ndim=4\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "No trials are completed yet.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-12-97aa1f44f4d2>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mstudy\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moptimize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mobjective\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mn_trials\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m20\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0;32mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstudy\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_params\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m//anaconda/lib/python2.7/site-packages/optuna/study.pyc\u001b[0m in \u001b[0;36mbest_params\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    110\u001b[0m         \"\"\"\n\u001b[1;32m    111\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 112\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_trial\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    113\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    114\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mproperty\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m//anaconda/lib/python2.7/site-packages/optuna/study.pyc\u001b[0m in \u001b[0;36mbest_trial\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    136\u001b[0m         \"\"\"\n\u001b[1;32m    137\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 138\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstorage\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_best_trial\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstudy_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    139\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    140\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mproperty\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m//anaconda/lib/python2.7/site-packages/optuna/storages/base.pyc\u001b[0m in \u001b[0;36mget_best_trial\u001b[0;34m(self, study_id)\u001b[0m\n\u001b[1;32m    165\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    166\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mall_trials\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 167\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'No trials are completed yet.'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    168\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    169\u001b[0m         \u001b[0;31m# TODO(sano): Deal with maximize direction.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: No trials are completed yet."
     ]
    }
   ],
   "source": [
    "study = optuna.create_study()\n",
    "study.optimize(objective, n_trials=20)\n",
    "\n",
    "print(study.best_params)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:anaconda]",
   "language": "python",
   "name": "conda-env-anaconda-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
